---
# tasks file for web
- name: create files dir locally
  local_action: file path={{ playbook_dir }}/files state=directory
  become: no
- name: create SSL cert locally
  local_action: >
    command openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -subj /CN=localhost -keyout {{ local_key_file }}
    -out {{ local_cert_file }} creates={{ local_key_file }} creates={{ local_cert_file }}
  become: no
- name: install nginx
  apt: name=nginx update_cache=yes cache_valid_time=3600
- name: create directories for TLS certificates
  file: path=/etc/nginx/ssl state=directory
- name: copy TLS key
  copy: src={{ local_key_file }} dest={{ key_file }} owner=root mode=0600
  notify: restart nginx
- name: copy TLS certificate
  copy: src={{ local_cert_file }} dest={{ cert_file }}
  notify: restart nginx
- name: copy nginx config file
  template: src=templates/nginx.conf.j2 dest={{ conf_file }}
  notify: restart nginx
- name: enable configuration
  file: dest=/etc/nginx/sites-enabled/default src={{ conf_file }} state=link
  notify: restart nginx
- name: copy public directory
  copy: src=public/ dest=/usr/share/nginx/html/
